#
# Module manifest for module 'sbanken-pwsh'
#
# Generated by: rs
#
# Generated on: 8/16/2020
#
@{
    RootModule        = 'sbanken-pwsh.psm1'
    ModuleVersion     = '0.0.1'
    GUID              = 'c0f78053-10c9-473a-85f8-f542fc14a855'

    Author            = 'Roberth Strand'
    CompanyName       = 'robstr.dev'

    Copyright         = 'sbanken-pwsh is licensed under the GNU General Public License v3.0'
    Description       = 'PowerShell wrapper for the Sbanken API'

    FunctionsToExport = '*'
    CmdletsToExport   = '*'
    VariablesToExport = '*'
    AliasesToExport   = '*'

    PrivateData       = @{
        PSData = @{
            Tags = @("Sbanken")
            ProjectUri = 'https://github.com/roberthstrand/sbanken-pwsh'
            # IconUri = ''
            # ReleaseNotes = ''
        }
    }
}


